language: node_js
node_js:
  - "10"
install:
  - yarn install
before_script:
  - yarn config set -- --emoji true
  - yarn update-core
script:
  - yarn dist

jobs:  
  include:
    - stage: build
      os: linux
      after_install: apt-get install -y bsdtar

    - stage: build
      os: osx

    - stage: build
      os: windows
