version: 1.0.{build}

build_script:

- ps: >-
    $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version

    yarn install

    git clone -b "v$($env:package_version)" --depth=1 https://github.com/MicroPad/Web.git tmp

    cd tmp/app

    yarn

    yarn build

    rm build/service-worker.js

    rm build/*.map

    rm build/static/*/*.map

    cp -r build ../../core

    cd ../..

    yarn build

    npx electron-builder

test: off

artifacts:

- path: dist/

deploy: off
